/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* top =  1  *)
(* src = "mux_e.v:5" *)
module mux_e(out_e, sel, data_in, reset, clk);
  (* src = "mux_e.v:25" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "mux_e.v:10" *)
  input clk;
  (* src = "mux_e.v:8" *)
  input [1:0] data_in;
  (* src = "mux_e.v:13" *)
  wire f_out_e;
  (* src = "mux_e.v:6" *)
  output out_e;
  (* src = "mux_e.v:9" *)
  input reset;
  (* src = "mux_e.v:7" *)
  input sel;
  NOT _08_ (
    .A(reset),
    .Y(_06_)
  );
  NOT _09_ (
    .A(sel),
    .Y(_07_)
  );
  NAND _10_ (
    .A(_06_),
    .B(f_out_e),
    .Y(_01_)
  );
  NAND _11_ (
    .A(data_in[1]),
    .B(sel),
    .Y(_02_)
  );
  NAND _12_ (
    .A(data_in[0]),
    .B(_07_),
    .Y(_03_)
  );
  NAND _13_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  NAND _14_ (
    .A(reset),
    .B(_04_),
    .Y(_05_)
  );
  NOT _15_ (
    .A(_05_),
    .Y(_00_)
  );
  NAND _16_ (
    .A(_01_),
    .B(_05_),
    .Y(out_e)
  );
  (* src = "mux_e.v:25" *)
  DFF _17_ (
    .C(clk),
    .D(_00_),
    .Q(f_out_e)
  );
endmodule
