/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* top =  1  *)
(* src = "mux_e.v:5" *)
module mux_e(out_e, sel, data_in, reset, clk);
  (* src = "mux_e.v:25" *)
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "mux_e.v:10" *)
  input clk;
  (* src = "mux_e.v:8" *)
  input [1:0] data_in;
  (* src = "mux_e.v:13" *)
  wire f_out_e;
  (* src = "mux_e.v:6" *)
  output out_e;
  (* src = "mux_e.v:9" *)
  input reset;
  (* src = "mux_e.v:7" *)
  input sel;
  INVX1 _4_ (
    .A(f_out_e),
    .Y(_2_)
  );
  INVX1 _5_ (
    .A(reset),
    .Y(_3_)
  );
  MUX2X1 _6_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .S(sel),
    .Y(_1_)
  );
  NOR2X1 _7_ (
    .A(_3_),
    .B(_1_),
    .Y(_0_)
  );
  MUX2X1 _8_ (
    .A(_2_),
    .B(_1_),
    .S(_3_),
    .Y(out_e)
  );
  (* src = "mux_e.v:25" *)
  DFFPOSX1 _9_ (
    .CLK(clk),
    .D(_0_),
    .Q(f_out_e)
  );
endmodule
